---
title: "GBM-RCTKG"
author: "s.s"
date: "2023-05-23"
output: html_document
---

### data cleaning
```{r}
#extract similar disease from Jaleal's cluster
t1 <- readxl::read_xlsx("disease_clusters_Jaleal.xlsx")
head(t1)
l_gbm <- t1[which(t1$Cluster==13),'GARD_Disease']
list.gbm <- l_gbm$GARD_Disease
class(list.gbm)
list.gbm[1]






```
### match and extract data of RCTKG
```{r}


df <- read.csv('aggregate.P3+4.csv', header = T, row.names = 1)

## mannually checking the file (mapping of disease)
```

### aggregation by GARDname
```{r}
dt <- read.csv("CT_GBMcluster.new.csv",header = T, row.names = 1)

dt.aggre <- aggregate(.~ GARD.GARDName, data = dt[,2:3], \(x)toString(unique(na.omit(x))), na.action = identity)

head(dt)
dim(dt)

dim(dt.aggre)
# [1] 18  2
head(dt.aggre)
```

#### Jacarrd similarity 
```{r}
# define function
jaccard <- function(a, b) {
    intersection = length(intersect(a, b))
    union = length(a) + length(b) - intersection
    return (intersection/union)
}


##
mt <- data.frame(matrix(ncol=6, nrow=0))
colnames(mt) <- c('diseasePair', 'Jaccard', 'sharedNumber', 'unsharedNumber', 'shared', 'unshared')

g = unlist(strsplit(dt.aggre[6,2],', '))
for (i in 1:nrow(dt.aggre)) {
 
    a = unlist(strsplit(dt.aggre[i,2],', '))
    Jaccard_dis = jaccard(a, g)
    
    if(Jaccard_dis != 0){
    diseasePair = paste('Glioblastoma', dt.aggre[i,1], sep = ' vs. ')
    shared = toString(intersect(a,g))
    sharedNumber = length(intersect(a,g))
    unshared = toString(c(setdiff(a,g),setdiff(g,a)))
    unsharedNumber = length(c(setdiff(a,g),setdiff(g,a)))
      
    mt[nrow(mt)+1,] <- c(diseasePair, Jaccard_dis, sharedNumber, unsharedNumber, shared, unshared)   
      
  }
}


dim(mt)

write.csv(mt, file = 'jaccard_GBM_Cluster.csv')

## explanation: no shared drugs of GBM and Jaleal's disease cluster. Indicating potential and new research opportunity
## next step verification: drug bank data & LINCS database
```
#### try drug bank--pending


